### ISSUE TITLE
Make the Makefile consistent with the podcast-decoding project if possible

### ISSUE THREAD

**Issue by hvgazula** [hvgazula/podcast-encoding#11]
@zkokaja Your thoughts are very much appreciated here. For **DS** you are using `aligned` datums but that's not the case with the encoding I believe. Do you have any ideas on how we can sync this?

**Comment by zkokaja** [comment]
I thought encoding is using an aligned version of glove and gpt2. Is that right?

**Comment by hvgazula** [comment]
> I thought encoding is using an aligned version of glove and gpt2. Is that right?

Yes
