### ISSUE TITLE
Scotty is atleast 3 times slower than tiger

### ISSUE THREAD

**Issue by hvgazula** [hvgazula/podcast-encoding#5]

**Comment by hvgazula** [comment]
it would be nice if the data can be moved to tiger and work from there in the near future

**Comment by hvgazula** [comment]
@zkokaja what do you think?

**Comment by zkokaja** [comment]
The data should already be there right? We should maintain a sync between the systems. If we're using git and have a good project structure (and seemed like your code accounts for which cluster it's running on), then we should be able to make it work on both, right?

**Comment by hvgazula** [comment]
Yes, as long as the data is synced between the two. The good thing about `tiger` is all the nodes are named `tiger` while that's not the case with `scotty` making [this](https://github.com/hvgazula/podcast-encoding/blob/main/podenc_main.py#L49) if-else condition slightly contrived

**Comment by hvgazula** [comment]
> The data should already be there right? We should maintain a sync between the systems. If we're using git and have a good project structure (and seemed like your code accounts for which cluster it's running on), then we should be able to make it work on both, right?

Also, the data structure is not exactly the same. There are some differences which we need to sort out after talking among ourselves.
